### ISSUE TITLE
Adjusting logo mark in the center

### ISSUE THREAD

**Issue by courtbee** [cloudnativelabs/kube-router.io#1]
Hey, sorry if this isn't the correct place to put this!

- [x] Remove circle styling
- [x] Change graphic of octopus so that there is a white background, otherwise the navbar + body bg poke through and it'd be nice to have one solid color there instead of two.

CSS for removing the circle styling:

`.navbar-custom .avatar-container .avatar img { border-radius: 0 !important; }`
`.navbar-custom .avatar-container .avatar-img-border { border-radius: 0 !important; box-shadow: 0 0 0 rgba(0,0,0,0) !important; }`

**Comment by bzub** [comment]
Thanks, this is the perfect place to discuss changes. :)

**Comment by murali-reddy** [comment]
Yup!! Feel free to throw in your ideas :)

**Comment by courtbee** [comment]
Updated test branch.

Had a minor css issue that was also fixed from my above stuff.

`.navbar-custom .avatar-container .avatar-img { border-radius: 0 !important; }`
