### ISSUE TITLE
Try out "jeblister/kube" theme

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router.io#4]
Hey @courtbee, the [use-theme-kube](https://github.com/cloudnativelabs/kube-router.io/tree/use-theme-kube) branch is a WIP to switch themes. I changed some of the templating, filenames, and other Hugo things to match what the theme expects.

The CSS will need to be changed to work with the new theme. Here's some info I found that might help you with that:
- [`static/css/custom.css`](https://github.com/cloudnativelabs/kube-router.io/blob/use-theme-kube/static/css/custom.css) is what the theme loads last for css
- [`themes/kube/static/css`](https://github.com/cloudnativelabs/kube-router.io/tree/use-theme-kube/themes/kube/static/css) contains a number of different css files that you may need to override
- I overrode the theme's [`layouts/_default/baseof.html`](https://github.com/cloudnativelabs/kube-router.io/blob/use-theme-kube/layouts/_default/baseof.html) and copied over your previous additions for typekit, etc.

Let me know if you need anything from me to help get the theme working for us. Some of the html/templates may need to be changed/overridden to put a logo at the top somewhere for example. So I can help with that when you know where you want logos to go. Thanks!

**Comment by bzub** [comment]
Deploy preview is here: https://use-theme-kube--kube-router.netlify.com/

**Comment by bzub** [comment]
I guess this theme uses a css/js framework. Hopefully that doesn't get in the way too much. The docs for it are here: https://themes.gohugo.io/theme/kube/docs/

@courtbee if you don't want to deal with the "kube" framework I can try ripping it out and only keep the hugo stuff + layouts. Let me know.

**Comment by courtbee** [comment]
@bzub if it implements JS similar to bootstrap then I can manage alright. I may not be able to write js but I can initiate it and set parameters. Docs are pretty straightforward in that regard.

**Comment by bzub** [comment]
Closing this as we went with a custom made site. Will turn that into a hugo theme later.
